import { create } from "zustand";

type ShoppingStoreState = {
  shoppingItems: string[];
};

export const useStore = create<ShoppingStoreState>()(() => ({
  shoppingItems: [
    "bread",
    "milk",
    "beer",
    "wine",
    "chips",
    "cobs",
    "tomatoes",
    "pizza",
    "garlic bread",
    "fish",
    "pasta",
    "pasta sauce",
    "curry sauce",
    "rice",
    "tea",
    "coffee",
    "pepsi",
    "chilli",
    "guacomole",
    "sour cream",
    "fajitas",
    "tortilla",
    "baguette",
    "cake",
    "potatoes",
    "chicken",
    "pie",
    "birthday card",
    "pork pie",
    "luncheon meat",
    "corned beef",
    "ham",
    "baked beans",
    "kidney beans",
    "bananas",
    "carrots",
    "peas",
    "biscuits",
    "cucumber",
    "lettuce",
    "mushrooms",
    "onion",
    "water",
    "crisps",
    "pepper",
    "salad",
    "cheese",
    "cream",
    "trifles",
    "yoghurt",
    "cheesecake",
    "eggs",
    "margarine",
    "soya milk",
    "bacon",
    "duck",
    "mashed potato",
    "mince",
    "sausages",
    "tuna",
    "vinegar",
    "salt",
    "gravy",
    "tomato sauce",
    "brown sauce",
    "salad cream",
    "mayonnaise",
    "salt",
    "fish fingers",
    "soup",
    "soap",
    "wash powder",
    "washing up liquid",
    "fabric conditioner",
    "yorkshire pudding",
    "notebook",
    "porridge",
    "spaghetti",
    "chocolate",
    "cider",
    "lemonade",
    "foil",
    "bathroom cleaner",
    "calgon",
    "kitchen cleaner",
    "kitchen roll",
    "pasty",
    "scouring pads",
  ],
}));
